export enum Skills {
    ProficiencyInBraille = 'Proficiency in Braille',
    AttentionToDetail = 'Attention to Detail',
    KeyboardingSkills = 'Keyboarding Skills',
    KnowledgeOfAccessibilityStandards = 'Knowledge of Accessibility Standards',
    CommunicationSkills = 'Communication Skills',
    AdaptiveTechnologyProficiency = 'Adaptive Technology Proficiency',
    ProficiencyInSignLanguage = 'Proficiency in Sign Language',
    Creativity = 'Creativity',
    OrganizationalSkills = 'Organizational Skills',
    KnowledgeOfVisualStorytellingTechniques = 'Knowledge of Visual Storytelling Techniques',
    ProficiencyInSpeechRecognitionSoftware = 'Proficiency in Speech Recognition Software',
    ProblemSolvingSkills = 'Problem Solving Skills',
    TeamManagementSkills = 'Team Management Skills',
    ExpertiseInAccessibilitySoftware = 'Expertise in Accessibility Software',
    FamiliarWithSensoryAwareCounselingTechniques = 'Familiar with Sensory-aware Counseling Techniques',
    TechSavviness = 'Tech Savviness',
    Flexibility = 'Flexibility',
    Adaptability = 'Adaptability',
    AccessibilityKnowledge = 'Accessibility Knowledge',
    TechnicalProficiency = 'Technical Proficiency',
    ContinuousLearningSkills = 'Continuous Learning Skills',
    TechLiteracy = 'Tech Literacy',
    VisualDesignSkills = 'Visual Design Skills',
    StrategicThinkingSkills = 'Strategic Thinking Skills',
    TeamCollaborationSkills = 'Team Collaboration Skills',
    AnalyticalSkills = 'Analytical Skills',
    CustomerCareSkills = 'Customer Care Skills',
    CriticalThinking = 'Critical Thinking',
    AccessibilityAwareness = 'Accessibility Awareness',
    ExcellentCommunicationAndInterpersonalSkills = 'Excellent Communication and Interpersonal Skills',
    KnowledgeOfCompanyPoliciesAndProcedures = 'Knowledge of Company Policies and Procedures',
    IndustryExpertise = 'Industry Expertise',
    NetworkingAbilities = 'Networking Abilities',
    TimeManagementSkills = 'Time Management Skills'
}

export enum JobTitles {
    BrailleTranscriptionist = 'Braille Transcriptionist',
    CustomerServiceRepresentative = 'Customer Service Representative',
    BlindnessRehabilitationSpecialist = 'Blindness Rehabilitation Specialist',
    Educator = 'Educator',
    GraphicDesigner = 'Graphic Designer',
    AdministrativeAssistant = 'Administrative Assistant',
    ContentCreator = 'Content Creator',
    DataEntrySpecialist = 'Data Entry Specialist',
    Transcriptionist = 'Transcriptionist',
    LifeSkillsTrainer = 'Life Skills Trainer',
    AssistiveTechnologySpecialist = 'Assistive Technology Specialist',
    RehabilitationCounselor = 'Rehabilitation Counselor',
    VirtualAssistant = 'Virtual Assistant',
    Copywriter = 'Copywriter',
    AccessibilityConsultant = 'Accessibility Consultant',
    OnlineTutor = 'Online Tutor',
    TelecommutingSoftwareEngineer = 'Telecommuting Software Engineer',
    SocialMediaManager = 'Social Media Manager',
    MarketingCoordinator = 'Marketing Coordinator',
    OfficeAssistant = 'Office Assistant',
    LibraryAssistant = 'Library Assistant',
    FoodServiceWorker = 'Food Service Worker',
    WebDesigner = 'Web Designer',
    FreelanceWriter = 'Freelance Writer',
    EducationalAssistant = 'Educational Assistant',
    HumanResourcesAssistant = 'Human Resources Assistant',
    Consultant = 'Consultant'
}

export enum Cities {
    NewYork = "New York",
    LosAngeles = "Los Angeles",
    Chicago = "Chicago",
    Houston = "Houston",
    Boston = "Boston",
    Philadelphia = "Philadelphia"
}
